begin;
select plan(20);

select has_table('public', 'suppliers', 'suppliers table exists');
select has_table('public', 'material_requirements', 'material requirements table exists');
select has_column('public', 'material_requirements', 'source_quote_line_item_id', 'requirements link to exact quote lines');
select has_column('public', 'material_requirements', 'quoted_quantity', 'quoted quantity is snapshotted');
select has_column('public', 'material_requirements', 'order_quantity', 'order quantity is operational');
select has_column('public', 'material_requirements', 'supplier_id', 'supplier selection is optional');
select has_column('public', 'material_requirements', 'status', 'requirements have an operational status');
select ok((select relrowsecurity from pg_class where oid = 'public.suppliers'::regclass), 'supplier RLS is enabled');
select ok((select relrowsecurity from pg_class where oid = 'public.material_requirements'::regclass), 'requirement RLS is enabled');
select ok(has_table_privilege('authenticated', 'public.suppliers', 'INSERT'), 'authenticated contractors can create suppliers');
select ok(has_table_privilege('authenticated', 'public.suppliers', 'DELETE'), 'authenticated contractors can delete suppliers');
select ok(has_table_privilege('authenticated', 'public.material_requirements', 'UPDATE'), 'authenticated contractors can edit operational requirements');
select ok(not has_table_privilege('authenticated', 'public.material_requirements', 'INSERT'), 'requirements are generated by acceptance only');
select ok(not has_table_privilege('anon', 'public.suppliers', 'SELECT'), 'anon cannot read suppliers');
select ok(not has_table_privilege('anon', 'public.material_requirements', 'SELECT'), 'anon cannot read requirements');
select ok((select count(*) from pg_constraint where conrelid = 'public.material_requirements'::regclass and conname = 'material_requirements_source_unique') = 1, 'source line requirement is unique');
select ok((select count(*) from pg_trigger where tgrelid = 'public.quotes'::regclass and tgname = 'quotes_create_material_requirements') = 1, 'acceptance material trigger exists');
select ok((select count(*) from pg_trigger where tgrelid = 'public.material_requirements'::regclass and tgname = 'material_requirements_validate') = 1, 'requirement validation trigger exists');
select ok(not has_function_privilege('authenticated', 'public.validate_material_requirement()', 'EXECUTE'), 'requirement trigger cannot be called directly');
select ok(not has_function_privilege('anon', 'public.create_material_requirements_for_accepted_quote()', 'EXECUTE'), 'acceptance trigger cannot be called directly');

select * from finish();
rollback;
