import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireContractor } from '@/lib/auth/require-contractor';
import { getMailboxSummary } from '@/lib/mailbox/connection';
import { formatEuros } from '@/lib/money/totals';
import { calculateInvoiceTotals } from '@/lib/invoices/totals';
import { updateInvoiceDraft, updateDeliveryStatusAction, setPaymentStatusAction, createFullCreditNote, retryInvoiceDocumentsAction } from '../actions';
import type { Invoice, InvoiceLineItem, InvoiceQuoteSource, Quote } from '@/lib/supabase/types';
import InvoiceEmailForm from '@/components/InvoiceEmailForm';
import InvoiceIssueButton from './InvoiceIssueButton';

export default async function InvoicePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { supabase, contractor } = await requireContractor();
  const [{ data: invoice }, { data: lines }, { data: events }, { data: sources }, mailbox] = await Promise.all([
    supabase.from('invoices').select('*').eq('id', id).single(),
    supabase.from('invoice_line_items').select('*').eq('invoice_id', id).order('sort_order'),
    supabase.from('invoice_events').select('*').eq('invoice_id', id).order('created_at', { ascending: false }),
    supabase.from('invoice_quote_sources').select('*').eq('invoice_id', id).order('created_at'),
    getMailboxSummary(contractor.id),
  ]);
  if (!invoice) notFound();
  const typed = invoice as Invoice;
  const typedLines = (lines ?? []) as InvoiceLineItem[];
  const typedSources = (sources ?? []) as InvoiceQuoteSource[];
  const { data: sourceQuotes } = typedSources.length
    ? await supabase.from('quotes').select('id, quote_number, quote_kind').in('id', typedSources.map((source) => source.quote_id))
    : { data: [] as Pick<Quote, 'id' | 'quote_number' | 'quote_kind'>[] };
  const totals = calculateInvoiceTotals(typedLines);
  const isDraft = typed.status === 'draft';
  const overdue = typed.status === 'issued' && typed.document_type === 'invoice' && !typed.paid_at && !!typed.due_date && typed.due_date < new Date().toISOString().slice(0, 10);
  return <main className="page-shell page-medium">
    <Link href="/facturen" className="back-link">← Terug naar facturen</Link>
    <header className="page-header"><div><p className="eyebrow">{typed.document_type === 'credit_note' ? 'Creditnota' : 'Factuur'}</p><h1 className="page-title">{typed.invoice_number ?? 'Conceptfactuur'}</h1><p className="page-subtitle">{typed.customer_name} · {formatEuros(typed.total_cents)}</p></div><span className={`badge ${typed.status === 'draft' ? 'badge-neutral' : typed.status === 'credited' ? 'badge-warning' : 'badge-success'}`}>{isDraft ? 'Concept' : typed.status === 'credited' ? 'Gecrediteerd' : overdue ? 'Vervallen' : typed.paid_at ? 'Betaald' : 'Uitgegeven'}</span></header>
    {isDraft ? <form action={updateInvoiceDraft} className="flex flex-col gap-5"><input type="hidden" name="invoice_id" value={typed.id} /><DraftFields invoice={typed} lines={typedLines} /><div className="flex flex-wrap gap-3"><button type="submit" className="btn btn-outline">Concept opslaan</button><InvoiceIssueButton /></div></form> : <>
      <section className="card grid gap-3 sm:grid-cols-2"><div><p className="label">Klant</p><p>{typed.customer_name}</p><p className="text-muted">{typed.customer_street ?? typed.customer_address}</p><p className="text-muted">{typed.customer_postal_code} {typed.customer_city}</p>{typed.customer_vat_number && <p className="text-muted">BTW {typed.customer_vat_number}</p>}</div><div><p className="label">Factuurgegevens</p><p>Datum: {typed.issue_date}</p><p>Prestatiedatum: {typed.delivery_date}</p>{typed.document_type === 'invoice' && <p>Vervaldag: {typed.due_date ?? '—'}</p>}<p>Referentie: {typed.buyer_reference}</p><p>Levering: {transportLabel(typed.transport_status)}</p>{typed.delivery_status_source === 'user' && <p className="text-muted">Status door gebruiker aangegeven</p>}</div></section>
      <section className="card"><h2 className="section-heading">Factuurbronnen</h2><div className="flex flex-col gap-2">{typedSources.length === 0 ? <p className="text-muted">Geen offertebron gekoppeld.</p> : typedSources.map((source) => { const quote = (sourceQuotes ?? []).find((item) => item.id === source.quote_id); return <p key={source.id}><strong>{quote?.quote_number ?? source.quote_id.slice(0, 8)}</strong> · {quote?.quote_kind === 'meerwerk' ? 'Meerwerkofferte' : 'Standaardofferte'}</p>; })}</div></section>
      <section className="card"><h2 className="section-heading">Documenten</h2>{typed.document_status === 'ready' ? <div className="flex flex-wrap gap-2"><a className="btn btn-outline" href={`/api/invoices/${typed.id}/document?type=pdf`}>Pdf downloaden</a>{typed.customer_type === 'business' && <a className="btn btn-outline" href={`/api/invoices/${typed.id}/document?type=ubl`}>Peppol XML downloaden</a>}</div> : <form action={retryInvoiceDocumentsAction}><input type="hidden" name="invoice_id" value={typed.id} /><p className="alert alert-critical mb-3">Documentgeneratie {typed.document_status === 'failed' ? 'mislukt' : 'is nog niet afgerond'}{typed.document_error ? `: ${typed.document_error}` : '.'}</p><button className="btn btn-outline" type="submit">Documenten opnieuw genereren</button></form>}{typed.customer_type === 'business' && typed.transport_status === 'ready' && <p className="alert alert-warning mt-4">Upload het XML-bestand in je Peppol-portaal. Een PDF via e-mail vervangt dit niet voor B2B.</p>}</section>
      {typed.customer_type === 'private' && <InvoiceEmailForm invoice={typed} mailbox={mailbox} companyName={contractor.company_name} />}
      <section className="card"><h2 className="section-heading">Opvolging</h2><div className="flex flex-wrap gap-2">{typed.document_type === 'invoice' && typed.status === 'issued' && <form action={setPaymentStatusAction}><input type="hidden" name="invoice_id" value={typed.id} /><input type="hidden" name="paid" value={typed.paid_at ? 'false' : 'true'} /><button className="btn btn-outline" type="submit">{typed.paid_at ? 'Markeer als onbetaald' : 'Markeer als betaald'}</button></form>}{typed.customer_type === 'business' && typed.delivery_channel === 'peppol_manual' && typed.status === 'issued' && <form action={updateDeliveryStatusAction} encType="multipart/form-data" className="flex flex-wrap gap-2"><input type="hidden" name="invoice_id" value={typed.id} /><select name="delivery_status" defaultValue={typed.business_response_status === 'accepted' ? 'accepted' : typed.business_response_status === 'rejected' ? 'rejected' : 'submitted'} className="field min-h-12 w-auto"><option value="submitted">Ingediend bij Peppol</option><option value="accepted">Aanvaard</option><option value="rejected">Geweigerd</option></select><input name="delivery_external_reference" placeholder="Externe referentie (optioneel)" className="field min-h-12 w-auto" /><label className="label flex items-center gap-2"><span>Bewijs</span><input name="receipt" type="file" accept="image/*,.pdf" className="field min-h-12 w-auto" /></label><button className="btn btn-outline" type="submit">Levering opslaan</button></form>}</div>{typed.delivery_receipt_path && <a className="mt-3 inline-block text-sm font-bold underline" href={`/api/invoices/${typed.id}/receipt`}>Ontvangstbewijs downloaden</a>}</section>
      {typed.document_type === 'invoice' && typed.status !== 'credited' && <section className="card"><h2 className="section-heading">Creditnota</h2><p className="section-copy">Maak één volledige creditnota wanneer deze factuur volledig moet worden teruggedraaid.</p><form action={createFullCreditNote}><input type="hidden" name="invoice_id" value={typed.id} /><button className="btn btn-danger" type="submit">Volledige creditnota maken</button></form></section>}
    </>}
    <section className="card mt-5"><h2 className="section-heading">Lijnen</h2>{typedLines.map((line) => <div key={line.id} className="totals-row"><span>{line.description} · {line.quantity} {line.unit}</span><span>{formatEuros(line.line_total_cents)}</span></div>)}<div className="totals-grand"><strong>Totaal</strong><strong>{formatEuros(totals.totalCents)}</strong></div></section>
    {events && events.length > 0 && <details className="card mt-5"><summary className="section-heading cursor-pointer">Historiek</summary><div className="mt-3 flex flex-col gap-2">{events.map((event) => <p key={event.id} className="text-sm text-muted">{new Date(event.created_at).toLocaleString('nl-BE')} · {event.event_type}</p>)}</div></details>}
  </main>;
}

function DraftFields({ invoice, lines }: { invoice: Invoice; lines: InvoiceLineItem[] }) {
  return <>
    <section className="card grid gap-4 sm:grid-cols-2"><h2 className="section-heading sm:col-span-2">Klant</h2>
      <label className="label flex flex-col gap-2 sm:col-span-2">Type<select name="customer_type" defaultValue={invoice.customer_type} className="field"><option value="private">Particulier (B2C)</option><option value="business">Onderneming (B2B / Peppol)</option></select></label>
      <label className="label flex flex-col gap-2 sm:col-span-2">Naam<input name="customer_name" required defaultValue={invoice.customer_name} className="field" /></label>
      <label className="label flex flex-col gap-2 sm:col-span-2">Adres (voor PDF)<input name="customer_address" required defaultValue={invoice.customer_address} className="field" /></label>
      <label className="label flex flex-col gap-2">Straat en nummer<input name="customer_street" required defaultValue={invoice.customer_street ?? ''} className="field" /></label><label className="label flex flex-col gap-2">Postcode<input name="customer_postal_code" required defaultValue={invoice.customer_postal_code ?? ''} className="field" /></label><label className="label flex flex-col gap-2">Gemeente<input name="customer_city" required defaultValue={invoice.customer_city ?? ''} className="field" /></label><label className="label flex flex-col gap-2">Landcode<input name="customer_country_code" required defaultValue={invoice.customer_country_code} className="field" /></label>
      <label className="label flex flex-col gap-2">E-mail<input name="customer_email" type="email" defaultValue={invoice.customer_email ?? ''} className="field" /></label><label className="label flex flex-col gap-2">Telefoon<input name="customer_phone" defaultValue={invoice.customer_phone ?? ''} className="field" /></label><label className="label flex flex-col gap-2">BTW-nummer<input name="customer_vat_number" defaultValue={invoice.customer_vat_number ?? ''} className="field" /></label><label className="label flex flex-col gap-2">KBO-nummer<input name="customer_enterprise_number" defaultValue={invoice.customer_enterprise_number ?? ''} className="field" /></label><label className="label flex flex-col gap-2 sm:col-span-2">Peppol-ID (automatisch als 0208:KBO)<input name="customer_peppol_id" readOnly defaultValue={invoice.customer_peppol_id ?? ''} className="field" /></label>
    </section>
    <section className="card grid gap-4 sm:grid-cols-2"><h2 className="section-heading sm:col-span-2">Facturatie</h2><label className="label flex flex-col gap-2">Factuurdatum<input name="issue_date" required type="date" defaultValue={invoice.issue_date ?? ''} className="field" /></label><label className="label flex flex-col gap-2">Prestatiedatum<input name="delivery_date" required type="date" defaultValue={invoice.delivery_date ?? ''} className="field" /></label><label className="label flex flex-col gap-2">Vervaldatum<input name="due_date" required type="date" defaultValue={invoice.due_date ?? ''} className="field" /></label><label className="label flex flex-col gap-2 sm:col-span-2">Kopersreferentie (verplicht voor B2B)<input name="buyer_reference" defaultValue={invoice.buyer_reference} className="field" /></label><label className="label flex items-center gap-3 sm:col-span-2"><input name="reverse_charge" type="checkbox" defaultChecked={invoice.vat_treatment === 'reverse_charge'} className="h-5 w-5" /> Binnenlandse verlegging van heffing</label><label className="label flex items-center gap-3 sm:col-span-2"><input name="reduced_vat_confirmed" type="checkbox" defaultChecked={invoice.reduced_vat_confirmed} className="h-5 w-5" /> Bevestig de voorwaarden en versievaste verklaring voor 6% renovatie-btw (alleen B2C)</label></section>
    <section className="card"><h2 className="section-heading">Lijnen</h2><div className="flex flex-col gap-4">{lines.map((line) => <div key={line.id} className="grid gap-2 rounded-xl bg-paper p-3 sm:grid-cols-2"><input type="hidden" name={`line_${line.id}_unit_code`} value={line.unit_code} /><input type="hidden" name={`line_${line.id}_source_quote_id`} value={line.source_quote_id ?? ''} /><input type="hidden" name={`line_${line.id}_source_quote_line_item_id`} value={line.source_quote_line_item_id ?? ''} /><label className="label flex flex-col gap-1 sm:col-span-2">Omschrijving<input name={`line_${line.id}_description`} defaultValue={line.description} className="field" /></label><label className="label flex flex-col gap-1">Aantal<input name={`line_${line.id}_quantity`} type="number" step="any" defaultValue={line.quantity} className="field" /></label><label className="label flex flex-col gap-1">Eenheid<input name={`line_${line.id}_unit`} defaultValue={line.unit} className="field" /></label><label className="label flex flex-col gap-1">Prijs per eenheid (€)<input name={`line_${line.id}_unit_price_euros`} type="number" step="0.01" defaultValue={(line.unit_price_cents / 100).toFixed(2)} className="field" /></label><label className="label flex flex-col gap-1">Btw<select name={`line_${line.id}_vat_rate`} defaultValue={line.vat_rate} className="field"><option value="0.06">6%</option><option value="0.21">21%</option></select></label></div>)}</div></section>
  </>;
}

function transportLabel(status: Invoice['transport_status']): string { return ({ not_sent: 'Nog niet verstuurd', ready: 'Klaar voor upload', queued: 'In wachtrij', submitted: 'Ingediend', delivered: 'Afgeleverd', failed: 'Mislukt' } as Record<string, string>)[status]; }
